"""empty message

Revision ID: 5c27579a956f
Revises: 
Create Date: 2022-02-08 21:07:49.383544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c27579a956f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('whisky',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('distillery', sa.String(length=64), nullable=True),
    sa.Column('edition', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=64), nullable=True),
    sa.Column('smokey', sa.Integer(), nullable=True),
    sa.Column('peaty', sa.Integer(), nullable=True),
    sa.Column('spicy', sa.Integer(), nullable=True),
    sa.Column('sweet', sa.Integer(), nullable=True),
    sa.Column('fresh_fruit', sa.Integer(), nullable=True),
    sa.Column('dried_fruit', sa.Integer(), nullable=True),
    sa.Column('red_fruit', sa.Integer(), nullable=True),
    sa.Column('feinty', sa.Integer(), nullable=True),
    sa.Column('floral', sa.Integer(), nullable=True),
    sa.Column('winey', sa.Integer(), nullable=True),
    sa.Column('oak', sa.Integer(), nullable=True),
    sa.Column('cereal', sa.Integer(), nullable=True),
    sa.Column('chocolate', sa.Integer(), nullable=True),
    sa.Column('finish', sa.String(length=32), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.Column('plot', sa.String(length=120), nullable=True),
    sa.Column('description', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_country', sa.String(length=32), nullable=True),
    sa.Column('user_gender', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whisky')
    op.drop_table('user')
    # ### end Alembic commands ###
